### ISSUE TITLE
Move this to org

### ISSUE THREAD

**Issue by Evizero** [Evizero/MLModels.jl#1]
@tbreloff I started by using a few things that I have already implemented. Why don't you establish the org and we move this there and we iterate on it. 

Near plans:
- ~~Flesh out data sources, especially for streaming data~~
- ~~Flesh out function definition and class hierachie~~
- ~~I think it would be cool to build on ROCAnalysis.jl and provide plots for it using Plots.jl~~

EDIT: plans are discussed and iterated on in other issues

**Comment by Evizero** [comment]
I gave you push access @tbreloff . This is as much your package as it is mine after all. If the package is a success then we should probably move it to some organisation sooner or later anyhow.

Naturally I do think that we should work in branches and create PRs to get something into master.

**Comment by tbreloff** [comment]
I think we should revisit moving the repo to JuliaML.  Thoughts?

**Comment by Evizero** [comment]
That's still the plan. I don't view this as "my" package.

But let's first make sure that a readme is present that shows what's going on and that enough tests are in place.

**Comment by Evizero** [comment]
tied to https://github.com/Evizero/LearnBase.jl/issues/15
