### ISSUE TITLE
Update to work with 0.5 changes

### ISSUE THREAD

**Issue by Evizero** [Evizero/MLModels.jl#19]
Some issues are upstream, but a few things could be done already

- [x] remove `call` overloads
- [x] Get rid of array views in favour of native `SubArrays` using `slice` and `sub`

**Comment by tbreloff** [comment]
> Get rid of array views

:+1:

**Comment by Evizero** [comment]
how should we handle recipes tests?

**Comment by tbreloff** [comment]
I think we leave them in MLPlots

**Comment by Evizero** [comment]
That seems like an unstable solution. related: https://github.com/JuliaML/ValueHistories.jl/issues/2#issuecomment-219217537
